name : productos_textiles_cw_hs12_ciiu4
longname :  Correspondencia clasificación productos textiles HS12 a CIIU Rev 4
url: https://github.com/insongkim/concordance
namespace: viabilidad_atractivo
assumptions: >
  Correspondencia clasificación productos textiles HS12 a CIIU Rev 4
  